### update request to example server
PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174014
Content-Type: application/json

{
    "dateOfBirth": "1987-10-17",
    "email": "smi.agga@example.com",
    "address": "789 Willow St, Springfield",
    "name": "Samir Walker",
    "id": "223e4567-e89b-12d3-a456-426614174014"
  }