spring.application.name=patient-service

spring.datasource.url=jdbc:postgresql://localhost:5434/practice_db
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=developer
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=4000
logging.level.root = info
